config:
  size:
    width: 400
    height: 400
state:
  init:
    foo!: 0
    on: 0
    off: 0
  update:
    on:
      foo: 1
    off:
      foo: 0
ui:
  ver:
    - toggle: foo
      style:
        color: olive
        secondary-color: blue
    - hor:
        - button: on
        - button: off
