config:
  size:
    width: 500
    height: 500
state:
  init:
    foo!: 0
    on: 0
    off: 0
  update:
    on:
      foo: 1
    off:
      foo: 0
ui:
  ver:
    - slider: foo
    - hor:
        - button: on
        - button: off
          scale: 2
    - space: []
      scale: 0.5
    - label: sd
      text: Hi there
    - hor:
        - knob: sdf
        - slider: on2
        - button: off2
